### ISSUE TITLE
Request for Extension 

### ISSUE THREAD

**Issue by souyazdi** [vincenzocoia/BAIT509#12]
Hello Vincezo,

I wanted to see if you could kindly give us one extra day to submit the assignment. 
Many of us have some unresolved questions which are hoping to ask you on Monday.
We would be grateful to you for your kind consideration.

**Comment by piyush7007** [comment]
I believe the request is legitimate as some parts of the assignment are time consuming. Therefore, I up vote this comment.

**Comment by vincenzocoia** [comment]
Okay, looks like the demand is high. I'll grant an extension until midnight -- that is, Monday March 12 at 24:00. Assignment 2 will still be released tomorrow. There will be time after we talk about regression/decision trees to talk about Assignment 1 and 2.

I'll make the changes to reflect this now.

**Comment by vincenzocoia** [comment]
Turns out Connect doesn't use the 24-hour clock, so can't accept a deadline of 24:00. I moved the deadline to 23:59.

**Comment by souyazdi** [comment]
Much appreciated
