### ISSUE TITLE
Hey MBAN! Ever wondered how Facebook uses machine learning to automatically recognize your friends to tag in your Photographs? Give it a read to know more!

### ISSUE THREAD

**Issue by dhruvatej** [vincenzocoia/BAIT509#3]
I have come across an interesting Issue: Improving detection of faces? #333 while skimming through the issues this morning. I couldn’t resist in deep diving into the concept to give you an idea of how it works. 

In the old days, we used to type in the name to tag a friend. Now as soon as you upload a picture, it tags/prompts their names to tag for you. Face recognition is the technology used by Facebook, an interesting concept for detecting faces using Python.

Detection Accuracy Percentage: 98%

Steps involved in Face Recognition:
1. Find face in the image (Uses Algorithm-Histogram of Oriented Gradients(HOG): Check under references to learn more)
2. Analyze facial features and focus on each face (Albeit in Bad lighting) and recognize if it is the same person. Pick the unique features like how big the eyes are, how long the face is. (Finding the landmarks)
3. Compare against known faces. (Uses Neural Network to measure facial features)
4.  And it’s a Match (Finds the name of a person using Classification and Simple Linear Regression Analysis by SVM Classifier Algorithm)

References
HOG - http://lear.inrialpes.fr/people/triggs/pubs/Dalal-cvpr05.pdf
HOG Python Code - https://gist.github.com/ageitgey/1c1cb1c60ace321868f7410d48c228e1
Face Landmark Estimation - http://www.csc.kth.se/~vahidk/papers/KazemiCVPR14.pdf
 Face Landmark Python Code- https://gist.github.com/ageitgey/ae340db3e493530d5e1f9c15292e5c74
SVM- https://en.wikipedia.org/wiki/Support_vector_machine

Link to the Issue: https://github.com/ageitgey/face_recognition/issues/333
The title of the issue better describes the issue the user faced. The user posted his work around clearly. Response to the issue is given in the form of a code. It is an effective solution proposed to the issue and the issue gets closed with a single response. Code snippet provided is very supportive for the issue to be resolved.

**Comment by ishakataria** [comment]
Thanks Dhruva for sharing this, it is indeed interesting!

**Comment by vincenzocoia** [comment]
This is great @dhruvatej! Thanks for sharing. Feel free to keep this Issue open!
