### ISSUE TITLE
Understanding commit/pull requests

### ISSUE THREAD

**Issue by nibeerdewan** [vincenzocoia/BAIT509#4]
Hi, 

As I was playing with GitHub I noticed there are options for committing and pull requests. Are each our repos say for ex: nibeerdewan/BAIT509  committed to vincenzocia:master branch? 
If yes, then how do we update our branch when Vincenzo or the TAs update course materials without a pull request? I noticed a message that said this on my repo, "This branch is 1 commit ahead, 5 commits behind vincenzocoia:master." Do we have to request a pull?

**Comment by vincenzocoia** [comment]
Hi @nibeerdewan, there's no need to do a pull request. A "pull request" means that you're requesting the `vincenzocoia/BAIT509` repo to be updated with the changes you made to your own `nibeerdewan/BAIT509`. 

> then how do we update our branch when Vincenzo or the TAs update course materials without a pull request?

As far as I know, you can only do this locally (on your own computer, not on GitHub). We might get around to this tomorrow.
